services:
  app-blue:
    container_name: app-blue
    image: ${ECR_IMAGE_URI}:${IMAGE_TAG}
    environment:
      PROFILE: dev
      TZ: Asia/Seoul
      HOSTNAME: ${HOSTNAME_BLUE:-dev-1-blue}
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - ./log/blue:/log
    networks:
      - app-network
    entrypoint: ["sh", "-c", "java $$JAVA_OPTS -Duser.timezone=Asia/Seoul -Dspring.profiles.active=dev -jar /app.jar"]

  app-green:
    container_name: app-green
    image: ${ECR_IMAGE_URI}:${IMAGE_TAG}
    environment:
      PROFILE: dev
      TZ: Asia/Seoul
      HOSTNAME: ${HOSTNAME_GREEN:-dev-1-green}
    ports:
      - "8081:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - ./log/green:/log
    networks:
      - app-network
    entrypoint: ["sh", "-c", "java $$JAVA_OPTS -Duser.timezone=Asia/Seoul -Dspring.profiles.active=dev -jar /app.jar"]

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ~/nginx-conf/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ~/nginx-conf/service-url.inc:/etc/nginx/conf.d/service-url.inc
    restart: always
    networks:
      - app-network

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    environment:
      TZ: Asia/Seoul
      MONITORING_INSTANCE: ${MONITORING_INSTANCE}
      ENVIRONMENT: ${ENVIRONMENT:-dev}
      SERVER_ID: ${SERVER_ID:-dev-1}
    env_file:
      - .env
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./log:/log
      - ./promtail-positions:/tmp/positions
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
