services:
  app-blue:
    container_name: app-blue
    image: ${ECR_IMAGE_URI}:${IMAGE_TAG}
    environment:
      PROFILE: dev
      TZ: Asia/Seoul
      SERVER_ID: ${SERVER_ID}
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - ./log:/log
      - server-tmp:/tmp
    networks:
      - app-network

  app-green:
    container_name: app-green
    image: ${ECR_IMAGE_URI}:${IMAGE_TAG}
    environment:
      PROFILE: dev
      TZ: Asia/Seoul
      SERVER_ID: ${SERVER_ID}
    ports:
      - "8081:8080"
    env_file:
      - .env
    restart: always
    volumes:
      - ./log:/log
      - server-tmp:/tmp
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ~/nginx-conf/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ~/nginx-conf/service-url.inc:/etc/nginx/conf.d/service-url.inc
    restart: always
    networks:
      - app-network

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    environment:
      TZ: Asia/Seoul
      MONITORING_INSTANCE: ${MONITORING_INSTANCE}
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./log:/log
      - server-tmp:/tmp
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml
    restart: always
    networks:
      - app-network

volumes:
  server-tmp:

networks:
  app-network:
    driver: bridge
