FROM eclipse-temurin:21-jdk-alpine
ARG JAR_FILE=build/libs/edukit-api.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Duser.timezone=Asia/Seoul -Dspring.profiles.active=prod -jar /app.jar"]
