server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://${MONITORING_INSTANCE}/loki/api/v1/push"

scrape_configs:
  # EduKit API 모듈 - 모든 로그 레벨
  - job_name: edukit-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: edukit-api
          module: api
          environment: ${ENVIRONMENT}
          host: ${HOSTNAME:-localhost}
          __path__: /log/**/*.log
    pipeline_stages:
      # JSON 로그 파싱
      - json:
          expressions:
            timestamp: timestamp
            level: level
            thread: thread
            logger: logger
            message: message
            traceId: traceId
            userId: userId
            requestUrl: requestUrl
            method: method

      # 헬스체크 및 메트릭 엔드포인트 필터링
      - drop:
          expression: '.*(/health|/actuator|/metrics|/prometheus|favicon\.ico).*'
          source: message

      # HTTP 메서드 기반 헬스체크 필터링
      - drop:
          expression: '.*(GET|POST|PUT|DELETE).*(actuator|health|metrics|prometheus).*'
          source: message

      # 동적 라벨 설정
      - labels:
          level:
          thread:
          logger:
          traceId:
          userId:
          requestUrl:
          method:

      # 타임스탬프 파싱
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000"
          location: "Asia/Seoul"


