server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: "http://${MONITORING_INSTANCE}/loki/api/v1/push"

scrape_configs:
  # API 모듈 - ERROR 로그
  - job_name: api_error_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: api_error_logs
          module: api
          level: error
          environment: ${ENVIRONMENT}
          __path__: /log/error/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            thread: thread
            logger: logger
            module: module
            environment: environment
            message: message

      - drop:
          expression: '.*(/health|/actuator|/metrics|/prometheus|favicon\.ico|GET.*200.*(/health|/actuator|/metrics)).*'
          source: message

      - drop:
          expression: '.*(GET|POST|PUT|DELETE).*(actuator|health|metrics|prometheus).*'
          source: message
      - labels:
          thread:
          logger:
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000"
          location: "Asia/Seoul"

  # API 모듈 - INFO 로그
  - job_name: api_info_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: api_info_logs
          module: api
          level: info
          environment: ${ENVIRONMENT}
          __path__: /log/info/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            thread: thread
            logger: logger
            module: module
            environment: environment
            message: message

      - drop:
          expression: '.*(/health|/actuator|/metrics|/prometheus|favicon\.ico|GET.*200.*(/health|/actuator|/metrics)).*'
          source: message

      - drop:
          expression: '.*(GET|POST|PUT|DELETE).*(actuator|health|metrics|prometheus).*'
          source: message
      - labels:
          thread:
          logger:
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000"
          location: "Asia/Seoul"

  # API 모듈 - WARN 로그
  - job_name: api_warn_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: api_warn_logs
          module: api
          level: warn
          environment: ${ENVIRONMENT}
          __path__: /log/warn/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            thread: thread
            logger: logger
            module: module
            environment: environment
            message: message

      - drop:
          expression: '.*(/health|/actuator|/metrics|/prometheus|favicon\.ico|GET.*200.*(/health|/actuator|/metrics)).*'
          source: message

      - drop:
          expression: '.*(GET|POST|PUT|DELETE).*(actuator|health|metrics|prometheus).*'
          source: message
      - labels:
          thread:
          logger:
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000"
          location: "Asia/Seoul"


