name: api-dev-ci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set timezone to Korea
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Seoul"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: build with gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test
